import * as TvDBTypes from "../../../src/server/tvdbClient/tvdbTypes";

// tslint:disable: max-line-length

export const onePieceId = 81797;
export const onePieceSeriesData: TvDBTypes.ISearchSeriesResponse = {
    data: [
        {
            aliases: [],
            banner: "graphical/81797-g2.jpg",
            firstAired: "1999-10-20",
            id: 81797,
            network: "Fuji TV",
            overview: `Wealth, fame, power ... a man had obtained everything in this world, he was the King of pirates.`,
            seriesName: "One Piece",
            slug: "one-piece",
            status: "Continuing",
        },
    ],
};

export const fireforceId = 355480;
export const fireForceEpisodes: TvDBTypes.ISeriesEpisodesResponseData = {
    links: {
        first: 1,
        last: 1,
        next: null,
        prev: null,
    },
    data: [
        {
            id: 6904794,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 1,
            episodeName: "Shinra Kusakabe Enlists",
            firstAired: "2019-07-06",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: "On his first day with Special Fire Force Company 8, Shinra Kusakabe, a third-generation pyrokinetic who is able to produces flames from his feet, meets his fellow company members and begins to fulfil his wish of becoming a hero.",
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1564452126,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 1,
            filename: "episodes/355480/6904794.jpg",
            seriesId: 355480,
            lastUpdatedBy: 482387,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 435425,
            thumbAdded: "2019-06-25 05:38:51",
            thumbWidth: "400",
            thumbHeight: "225",
            imdbId: "tt9848418",
            siteRating: 0,
            siteRatingCount: 0,
        },
        {
            id: 7244048,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 2,
            episodeName: "The Heart of a Fire Soldier",
            firstAired: "2019-07-13",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: "Arthur Boyle, the self-professed \"Knight King,\" arrives at Company 8, and immediately, there are tensions between him and Shinra. With the Rookie Games coming up, Hinawa wants to see what the two new recruits are really capable of.",
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1563751452,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 2,
            filename: "episodes/355480/7244048.jpg",
            seriesId: 355480,
            lastUpdatedBy: 482387,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 435425,
            thumbAdded: "2019-07-09 09:41:06",
            thumbWidth: "400",
            thumbHeight: "225",
            imdbId: "tt10483528",
            siteRating: 0,
            siteRatingCount: 0,
        },
        {
            id: 7244049,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 3,
            episodeName: "The Rookie Fire Soldier Games",
            firstAired: "2019-07-27",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: "Shinra and Arthur compete in the Rookie Fire Soldier Games, a contest to test the abilities of each year's newest recruits. However, they are interrupted at the goal by the mysterious man who created explosions at their last fire scene.",
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1564452228,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 3,
            filename: "episodes/355480/7244049.jpg",
            seriesId: 355480,
            lastUpdatedBy: 482387,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 435425,
            thumbAdded: "2019-07-15 23:43:22",
            thumbWidth: "400",
            thumbHeight: "225",
            imdbId: "tt10483530",
            siteRating: 0,
            siteRatingCount: 0,
        },
        {
            id: 7244052,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 4,
            episodeName: "The Hero and the Princess",
            firstAired: "2019-08-03",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: "A call mistakenly comes in to Company 8 to rescue a dog out of a tree, to which Shinra and Arthur respond. However, when an Infernal suddenly appears at the district courthouse, the two must play catch-up to join the rest of the company.\r\n",
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1564852781,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 4,
            filename: "episodes/355480/7244052.jpg",
            seriesId: 355480,
            lastUpdatedBy: 463441,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 435425,
            thumbAdded: "2019-08-02 23:27:57",
            thumbWidth: "400",
            thumbHeight: "225",
            imdbId: "tt10483532",
            siteRating: 0,
            siteRatingCount: 0,
        },
        {
            id: 7244053,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 5,
            episodeName: "The Battle Begins",
            firstAired: "2019-08-10",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: null,
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1564831307,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 5,
            filename: "",
            seriesId: 355480,
            lastUpdatedBy: 513322,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 1,
            thumbAdded: "",
            thumbWidth: null,
            thumbHeight: null,
            imdbId: "tt10483534",
            siteRating: 0,
            siteRatingCount: 0,
        },
        {
            id: 7244056,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 6,
            episodeName: "Episode 6",
            firstAired: "2019-08-17",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: null,
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1563555431,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 6,
            filename: "",
            seriesId: 355480,
            lastUpdatedBy: 464876,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 1,
            thumbAdded: "",
            thumbWidth: null,
            thumbHeight: null,
            imdbId: "tt10483538",
            siteRating: 0,
            siteRatingCount: 0,
        },
        {
            id: 7244058,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 7,
            episodeName: "Episode 7",
            firstAired: "2019-08-24",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: null,
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1563555444,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 7,
            filename: "",
            seriesId: 355480,
            lastUpdatedBy: 464876,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 1,
            thumbAdded: "",
            thumbWidth: null,
            thumbHeight: null,
            imdbId: "tt10483540",
            siteRating: 0,
            siteRatingCount: 0,
        },
        {
            id: 7244062,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 8,
            episodeName: "Episode 8",
            firstAired: "2019-08-31",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: null,
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1563555455,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 8,
            filename: "",
            seriesId: 355480,
            lastUpdatedBy: 464876,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 1,
            thumbAdded: "",
            thumbWidth: null,
            thumbHeight: null,
            imdbId: "tt10483542",
            siteRating: 0,
            siteRatingCount: 0,
        },
        {
            id: 7244063,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 9,
            episodeName: "Episode 9",
            firstAired: "2019-09-07",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: null,
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1563555466,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 9,
            filename: "",
            seriesId: 355480,
            lastUpdatedBy: 464876,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 1,
            thumbAdded: "",
            thumbWidth: null,
            thumbHeight: null,
            imdbId: "tt10483546",
            siteRating: 0,
            siteRatingCount: 0,
        },
        {
            id: 7244067,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 10,
            episodeName: "Episode 10",
            firstAired: "2019-09-14",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: null,
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1563559471,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 10,
            filename: "",
            seriesId: 355480,
            lastUpdatedBy: 464876,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 1,
            thumbAdded: "",
            thumbWidth: null,
            thumbHeight: null,
            imdbId: "tt10483548",
            siteRating: 0,
            siteRatingCount: 0,
        },
        {
            id: 7244070,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 11,
            episodeName: "Episode 11",
            firstAired: "2019-09-21",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: null,
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1563559487,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 11,
            filename: "",
            seriesId: 355480,
            lastUpdatedBy: 464876,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 1,
            thumbAdded: "",
            thumbWidth: null,
            thumbHeight: null,
            imdbId: "tt10483550",
            siteRating: 0,
            siteRatingCount: 0,
        },
        {
            id: 7244077,
            airedSeason: 1,
            airedSeasonID: 786276,
            airedEpisodeNumber: 12,
            episodeName: "Episode 12",
            firstAired: "2019-09-28",
            guestStars: [],
            director: "||",
            directors: [],
            writers: [],
            overview: null,
            language: {
                episodeName: "en",
                overview: "en",
            },
            productionCode: "",
            showUrl: "",
            lastUpdated: 1563559500,
            dvdDiscid: "",
            dvdSeason: 0,
            dvdEpisodeNumber: 0,
            dvdChapter: null,
            absoluteNumber: 12,
            filename: "",
            seriesId: 355480,
            lastUpdatedBy: 464876,
            airsAfterSeason: null,
            airsBeforeSeason: null,
            airsBeforeEpisode: null,
            thumbAuthor: 1,
            thumbAdded: "",
            thumbWidth: null,
            thumbHeight: null,
            imdbId: "tt10483552",
            siteRating: 0,
            siteRatingCount: 0,
        },
    ],
};

describe("Ignore Tests", () => {
    it(`blah`, () => {
        expect(true).toBeTruthy();
    });
});
